# -*- coding: utf-8 -*-
"""Coursework 01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOniKtI4L3uDWBzXxQDFSx_EoFdW5F1V
"""

from bokeh.io import output_notebook, show
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool
import pandas as pd

output_notebook()

df = pd.read_csv('species.csv')

county_data = df.groupby('county_id')['habitat_yearround_pct'].mean().reset_index()

def make_plot(doc):
    source = ColumnDataSource(county_data)

    p = figure(title="Geospatial Habitat Distribution",
               x_axis_label='County ID', y_axis_label='Habitat %',
               tools="pan,wheel_zoom,box_zoom,reset")

    p.circle('county_id', 'habitat_yearround_pct', size=10, source=source,
             fill_alpha=0.6, line_color=None)

    hover = HoverTool()
    hover.tooltips = [("County ID", "@county_id"), ("Habitat %", "@habitat_yearround_pct")]
    p.add_tools(hover)

    doc.add_root(p)

requirements_content = """
bokeh==3.3.0
pandas==2.1.0
numpy
"""

with open("requirements.txt", "w") as f:
    f.write(requirements_content.strip())

print("requirements.txt created successfully!")

!pip freeze > requirements.txt

