# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAGyGpwoOQn4OSXGhibB69jcdYZkWhV9
"""

requirements_content = """
bokeh==3.3.0
pandas==2.1.0
numpy
"""

with open("requirements.txt", "w") as f:
    f.write(requirements_content.strip())

print("requirements.txt created successfully!")

